version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "commonjs"
  environment = ["browser"]
  style_guide = "standard"

[[transformers]]
name = "standardjs"
enabled = true